#!/usr/bin/env python3
import sys ,os ,time
import webbrowser


def Hasan(Domain):
	Google =  ["site:"+Domain+" ext:bkf | ext:bkp | ext:bak | ext:old | ext:backup","site:"+Domain+" inurl:readme | inurl:license | inurl:install | inurl:setup | inurl:config","site:"+Domain+" ext:xml | ext:conf | ext:cnf | ext:reg | ext:inf | ext:rdp | ext:cfg | ext:txt | ext:ora | ext:ini","site:"+Domain+" ext:sql | ext:dbf | ext:mdb","site:"+Domain+" ext:log","site:"+Domain+" inurl:login","site:"+Domain+" inurl:Admin Login","site:*."+Domain]
	try:
		for URL in Google:		
			print(URL)
			webbrowser.open("https://www.google.com/search?q="+URL)
	except KeyboardInterrupt:
		os._exit(1)
	except:
		pass


if __name__ == '__main__':
	try:
		Domain = sys.argv[1]
		Hasan(Domain.strip())
	except IndexError:
		try:
			Domains = sys.stdin.readlines()
			if len(Domains) <1:
				os._exit(1)
			for Domain in Domains:
				Hasan(Domain.strip())
		except KeyboardInterrupt:
			os._exit(1)
