#!/usr/bin/env python3
import sys ,os ,time
import webbrowser

def Hasan(Domain):
	Github = ['"'+Domain+'" "password":','"'+Domain+'" "LdapUsername":','"'+Domain+'" "ConnectionStrings":','"'+Domain+'" string _password =','"'+Domain+'" auth ','"'+Domain+'" filetype:yaml mongodb','"'+Domain+'" email and password','"'+Domain+'" secret_access_key','"'+Domain+'" filename:sftp-config.json password','"'+Domain+'" api_tokan','"'+Domain+'" secret_key','"'+Domain+'" db_username and db password','"'+Domain+'" credentials aws_access_id','"'+Domain+'" authoriztion']
	try:
		for URL in Github:		
			print(URL)
			webbrowser.open("https://www.google.com/search?q="+URL)
	except KeyboardInterrupt:
		os._exit(1)
	except:
		pass


if __name__ == '__main__':
	try:
		Domain = sys.argv[1]
		Hasan(Domain.strip())
	except IndexError:
		try:
			Domains = sys.stdin.readlines()
			if len(Domains) <1:
				os._exit(1)
			for Domain in Domains:
				Hasan(Domain.strip())
		except KeyboardInterrupt:
			os._exit(1)
